# Render.com deployment configuration for NodeBB
services:
  - type: web
    name: big-love-nodebb
    env: docker
    dockerfilePath: ./deployment/Dockerfile
    dockerContext: .
    region: oregon  # Change to singapore for closer to Hong Kong
    plan: free  # Free web service
    buildCommand: echo "Building NodeBB with Docker"
    startCommand: ""  # Uses Dockerfile ENTRYPOINT
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: NODEBB_SECRET
        generateValue: true  # Auto-generate secret
      - key: URL
        fromService:
          type: web
          name: big-love-nodebb
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: big-love-postgres
          property: connectionString
      - key: PORT
        value: 4567
    autoDeploy: true

databases:
  - name: big-love-postgres
    databaseName: nodebb
    user: nodebb
    plan: free  # Free PostgreSQL plan


