name: big_love_app
description: A community app for sharing and interaction
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^12.1.3
  
  # Enhanced State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Networking
  http: ^1.5.0
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Media & Files
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  # file_picker: ^6.1.1  # Disabled due to V1 embedding issues
  path_provider: ^2.1.2
  
  # UI Enhancements & Animations
  flutter_animate: ^4.3.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  
  # Emoji & Reactions
  emoji_picker_flutter: ^1.6.3
  
  # Rich Text & Content
  flutter_quill: ^11.4.2
  markdown: ^7.2.2
  flutter_highlight: ^0.7.0
  
  # Utils & Helpers
  intl: any
  timeago: ^3.6.0
  url_launcher: ^6.2.2
  uuid: ^4.2.1
  collection: ^1.18.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  
  # Real-time (for future phases)
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/